train: data/test_950113/kana/gt/train.txt
valid: data/test_950113/kana/gt/valid.txt
savedir: data/test_950113/models/rnn_tokenizer
batch_size: 20
unroll_size: 20
char_embedding_dim: 64
chartype_embedding_dim: 8
hidden_size: 200
dropout: 0
max_epochs: 50
