train: data/test_950113/kana/gt/train.txt
valid: data/test_950113/kana/gt/valid.txt
level: 2
savedir: data/test_950113/models/rnn_tagger_2
batch_size: 20
unroll_size: 20
char_embedding_dim: 64
chartype_embedding_dim: 8
word_embedding_dim: 100
hidden_size: 200
dropout: 0
max_epochs: 50
